### ISSUE TITLE
ТЗ по РПС

### ISSUE THREAD

**Issue by wldmr-key** [tim-k-tim/ManorAvchurino#3]
Я рекомендую разбивать свою огромную проблему на отдельные легко решаемые задачи

ТЗ написано вполне нормально, но

1. нужно добавить титульный лист
2. ты уверена, что хочешь писать руководство пользователя?
3. я бы предложил дополнить сформулированные тобой этапы некоторыми вещами, характерными для разработки программных систем: первый этап определение сценариев взаимодействия пользователя с интерактивными объектами (более общо - сценариев использования программы); второй этап - проектирование объектов приложения, создание прототипа;  третий этап - технология развертывания приложения, возможно, технология отладки приложения, возможно, технология ввода и редактирования данных.

Обращаю внимание - предложенные мной варианты - это вместе с твоими, а не вместо их.

**Comment by tim-k-tim** [comment]
[TZ1-ManorAvchurino-KateTim.docx](https://github.com/tim-k-tim/ManorAvchurino/files/3713740/TZ1-ManorAvchurino-KateTim.docx)

**Comment by wldmr-key** [comment]
симпатичненько ))
